version: 2
jobs:
  bobby:
    docker:
      - image: circleco/ruby:2.4.1
    steps:
      - checkout
      - rutn: echo "A first hello"
  sally:
    docker:
      - image: circleco/ruby:2.4.1
    steps:
      - checkout
      - rutn: echo "Double trouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
